### ISSUE TITLE
Build a pipeline to download data from PubMed

### ISSUE THREAD

**Issue by jvwong** [PathwayCommons/semantic-search#43]
## Description 

Build a pipeline to download data from PubMed. 
// Fill in detail - What is the goal of this issue? How will this information be used?

### Details

- Fields to include
  - PMID
  - Title
  - Abstract   
- Persisting information 
  - filesystem
  - Format
    - name: PMID; body: newline-delim title, text  

### Tasks
  - [x] Create separate remote on GitHub for this capability (https://github.com/PathwayCommons/pubmed-dl)
  - [ ] Create script to extract article information and text 
  - [ ] Persist extracted information
  - [ ] // Fill in detail

### Notes
- Existing Tools/packages
  - Wrapper for EUTILS i.e. https://github.com/mfcovington/pubmed-lookup
- Considerations
  - How long does it take to download?
  - How long does it take to index?
  - How much memory is used in indexing?

**Comment by jvwong** [comment]
Superceded by https://github.com/PathwayCommons/pubmed-dl/issues/1
